services:
  db:
    image: postgres
    container_name: cuidapp_db
    environment:
      POSTGRES_USER: cuidapp
      POSTGRES_PASSWORD: qanova
      POSTGRES_DB: cuidapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
volumes:
  db_data:
